server:
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx

configs:
  secret:
    hosts:
      - argo
    paths:
      - /
  params:
    server.insecure: true

  credentialTemplates:
    ssh-creds1:
      url: "git@github.com:ronsha001/devtube-infrastructure.git"
    ssh-creds2:
      url: "git@github.com:ronsha001/devtube-chart.git"
  
  repositories:
    private-repo1:
      url: "git@github.com:ronsha001/devtube-infrastructure.git"
      name: "devtube-infras"
    private-repo2:
      url: "git@github.com:ronsha001/devtube-chart.git"
      name: "devtube-chart"

extraObjects:
  - apiVersion: argoproj.io/v1alpha1
    kind: Application
    metadata:
      name: app-of-apps
      namespace: argocd
      finalizers:
      - resources-finalizer.argocd.argoproj.io
    spec:
      project: default

      source:
        repoURL: git@github.com:ronsha001/devtube-infrastructure.git
        targetRevision: HEAD
        path: infra-apps
      destination:
        server: https://kubernetes.default.svc
        namespace: argocd

      syncPolicy:
        syncOptions:
        - CreateNamespace=true
        automated:
          selfHeal: true
          prune: true
  - apiVersion: argoproj.io/v1alpha1
    kind: Application
    metadata:
      name: devtube
      namespace: argocd
      finalizers:
      - resources-finalizer.argocd.argoproj.io
    spec:
      project: default
      source:
        repoURL: git@github.com:ronsha001/devtube-chart.git
        path: devtube
        targetRevision: HEAD

      destination:
        server: https://kubernetes.default.svc
        namespace: devtube

      syncPolicy:
        syncOptions:
        - CreateNamespace=true

        automated:
          selfHeal: true
          prune: true

# argocd:
#   applications:
#     - name: apps
#       project: default
#       metadata:
#         name: app-of-apps
#         namespace: argocd
#         finalizers:
#         - resources-finalizer.argocd.argoproj.io
#       source:
#         repoURL: git@github.com:ronsha001/devtube-infrastructure.git
#         targetRevision: HEAD
#         path: infra-apps
#       destination:
#         server: https://kubernetes.default.svc
#         namespace: argocd
#       syncPolicy:
#         syncOptions:
#         - CreateNamespace=true
#         automated:
#           selfHeal: true
#           prune: true