server:
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx

configs:
  secret:
    hosts:
      - argo
    paths:
      - /
  params:
    server.insecure: true

  credentialTemplates:
    ssh-creds1:
      url: "git@github.com:ronsha001/devtube-infrastructure.git"
    ssh-creds2:
      url: "git@github.com:ronsha001/devtube-chart.git"
  
  repositories:
    private-repo1:
      url: "git@github.com:ronsha001/devtube-infrastructure.git"
      name: "devtube-infras"
    private-repo2:
      url: "git@github.com:ronsha001/devtube-chart.git"
      name: "devtube-chart"