apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: secret-credentials
  namespace: devtube
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: azure-store

  target:
    name: secret-credentials
    creationPolicy: Owner

  data:
  # name of the SECRET in the Azure KV (no prefix is by default a SECRET)
  - secretKey: react-api-key
    remoteRef:
      key: react-api-key

  # explicit type and name of secret in the Azure KV
  - secretKey: react-app-id
    remoteRef:
      key: secret/react-app-id

  - secretKey: react-auth-domain
    remoteRef:
      key: secret/react-auth-domain

  - secretKey: react-messaging-senderId
    remoteRef:
      key: secret/react-messaging-senderId

  - secretKey: react-project-id
    remoteRef:
      key: secret/react-project-id
      
  - secretKey: react-storage-bucket
    remoteRef:
      key: secret/react-storage-bucket

  - secretKey: jwt-key
    remoteRef:
      key: secret/jwt-key

  - secretKey: root-user
    remoteRef:
      key: secret/root-user

  - secretKey: root-password
    remoteRef:
      key: secret/root-password