apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kibana
  namespace: default
spec:
  project: default

  source:
    helm:
      values: |
        resources:
          requests:
            cpu: "100m"
          limits:
            cpu: "1000m"
        service:
          type: "LoadBalancer"

    repoURL: https://helm.elastic.co
    chart: kibana
    targetRevision: 7.17.3
  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
